name: WAF Smoke Test

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays
  workflow_dispatch:     # Manual trigger

jobs:
  waf-smoke-test:
    runs-on: ubuntu-latest
    steps:
    # Ensure the repository is checked out for running the script
    # If running locally, you can use: git clone git@github.com:realad/waf-testing.git
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run WAF test
      run: |
        chmod +x ./tools/smoke-test/waf-smoke-test.sh
        ./tools/smoke-test/waf-smoke-test.sh "${{ secrets.WAF_TEST_URL }}"
