name: WAF Smoke Test

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays
  workflow_dispatch:     # Manual trigger

jobs:
  test-waf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: git@github.com:realad/waf-testing.git
    - name: Run WAF test
      working-directory: tools/smoke-test
      run: |
        chmod +x ./waf-smoke-test.sh
        ./waf-smoke-test.sh "${{ env.URL }}" -o report.md
